### ISSUE TITLE
Toggle Commit head details view on commit head click

### ISSUE THREAD

**Issue by trkaplan** [krasimir/poet.codes.feedback#1]
A UX case.
That would be better to **exit commit state** on **edit** button click in head commit. At the moment there is only one way to exit **commit edit state**, clicking **cancel** at the moment.

**Comment by krasimir** [comment]
Good idea. I also missed to document this UI. You can exit also if you press Esc key. Will implement what you are suggesting.

**Comment by krasimir** [comment]
Done.
