### ISSUE TITLE
Virtual blockchain (JS VM)

### ISSUE THREAD

**Issue by Swader** [krasimir/poet.codes.feedback#2]
See remix.ethereum.org for example.

Implement a JS-based local blockchain simulation in a template as a dependency, so that Solidity and Vyper functionality can be used in stories.

More resources:

- [remix.ethereum.org](http://remix.ethereum.org)
- [Vyper](https://github.com/ethereum/vyper)
- [Solidity](https://solidity.readthedocs.io/en/v0.5.3/)
- [Ganache](https://truffleframework.com/ganache)
- [Truffle](https://truffleframework.com/)
- [Embark](https://embark.status.im)

Can probably help with this in some way. There's more tools we could add here.

**Comment by krasimir** [comment]
I agree. We can add a lot of things in the Poet editor but what I'm trying to do is to keep it agnostic of the context that is put in. So instead of giving the write ability to create mindmaps I would give him/her a feature to create a diagram so he/she can create mindmaps.

**Comment by Swader** [comment]
Agreed. So a manual pull-in of selected deps like JSbin etc would be best, yes?

**Comment by krasimir** [comment]
Yep. [Here](https://poet.codes/e/LMXqqQ4WgUj) for example we have React and ReactDOM loaded on demand (registered as dependencies of the Story). Poet app itself is not built with React and it is not aware of it.

**Comment by krasimir** [comment]
By the way this morning I updated the docs page with a new `Writing` section. It may be interested to you if you want to write https://poet.codes/docs#writing

**Comment by Swader** [comment]
Absolutely. I have the perfect first candidate post, but it'll be using Nim as the programming language. Let's see how that works out, I'll be experimenting with it in the coming days.

**Comment by krasimir** [comment]
@Swader awesome. Let me know here if meet any problems.

**Comment by Swader** [comment]
I'm wondering how I could add `*.nim` syntax highlighting to the rendered /story?

**Comment by krasimir** [comment]
You can't to do that on your own. I'll do it today or probably tomorrow. You'll have to use

```
```nim
... something here
```

It is possible because it is supported by https://prismjs.com and it is just 1K). Can you give me a link to your story so I can test.

**Comment by Swader** [comment]
Sure: https://poet.codes/e/VB2EkkWlOS4#upd.nim

The injected file syntax is what I'm curious about, there's no way to code fence that, is there?

**Comment by krasimir** [comment]
The code here https://poet.codes/s/VB2EkkWlOS4/nimbus-state-transition will be syntax-highlighted tomorrow. The thing which can not be is the code in the editor (the link that you provided). Or in other words while you are writing the code. That is because I'm using CodeMirror there and I'm a little bit reserved to provide support of many languages due to file size.

**Comment by Swader** [comment]
That's all I want, thanks! As long as people looking at the final rendering can see syntax colors I'm good with that, cheers!

Sidenote - being able to define dependencies for the editor as well would be an okay solution to the syntax highlight problem, and would open the door towards the OP of this issue - a virtual blockchain inside the editor itself a-la remix.ethereum.org

**Comment by krasimir** [comment]
@Swader it's done 
![image](https://user-images.githubusercontent.com/528677/52762524-b416f180-3020-11e9-80fa-bc146cabbbf3.png)
It's not line Prismjs is providing so much syntax-highlighting but it is better then nothing.

**Comment by Swader** [comment]
Indeed, thank you!
